### ISSUE TITLE
 关于结果 About the results

### ISSUE THREAD

**Issue by MasterBeluga** [Mr-TalhaIlyas/scripts#2]
Is this the code you reproduced? How about the effect? Because I can't understand another SegNext code, I want to use your code

**Comment by Mr-TalhaIlyas** [comment]
Yes,  I reproduced the code tested it on several lab datasets. But I couldn't find the time to reproduce the results in paper. I trained it on cityscape though, from scratch, it seems to be working fine. I updated the readme with results.

**Comment by MasterBeluga** [comment]
谢谢您的答复
